name: Deployment

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  pages: write
  id-token: write

concurrency:
  group: deployment
  cancel-in-progress: true

jobs:
  deployment:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - uses: typst-community/setup-typst@v3
        with:
          typst-version: ^0.13.0
        env:
          GH_TOKEN: ${{ github.token }}
      - run: echo "show_mobile = false" >> config.toml
      - run: mkdir www
      - run: typst compile --font-path fonts resume.typ www/resume-gidongkwon.pdf
      - run: typst compile --font-path fonts portfolio.typ www/portfolio-gidongkwon.pdf
      - uses: actions/configure-pages@v4
      - uses: actions/upload-pages-artifact@v3
        with:
          path: www
      - uses: actions/deploy-pages@v4